blank_issues_enabled: false
contact_links:
  - name: ğŸ’¡ Suggestions ğŸ’¡
    url: https://github.com/basecamp/omarchy/discussions/categories/suggestions
    about: Suggest new features, changes to existing, or other ideas.
  - name: ğŸ›Ÿ Support ğŸ›Ÿ
    url: https://omarchy.org/discord
    about: Need help? Join our Discord community for support with any issues. GitHub issues should be used for verified bugs, documentation, and enhancement proposals only.
